{{-- Bunga: blush and peach, the most floral of the four. --}}
@include('sites.partials.card', ['site' => $site, 'preview' => $preview, 'palette' => [
    'tone' => 'light',
    'eyebrow' => 'Kami Akan Berkahwin',
    'page' => 'bg-[#fff6f7] text-[#5b3746]',
    'name' => 'text-[#8f4257]',
    'amp' => 'text-[#d98ca6]',
    'body' => 'text-[#8a6172]',
    'muted' => 'text-[#c096a5]',
    'floral' => '#d98ca6',
    'accent' => '#e8b06a',
    'petals' => ['#f7c9d6', '#f3b8c8', '#fbdcc4', '#f8d5e0'],
    'petalOpacity' => '0.8',
    'panel' => 'border-[#f3d7de] bg-white/75',
    'button' => 'bg-[#d98ca6] text-white hover:bg-[#c4728e]',
    'ring' => 'ring-white',
    'rail' => 'border-[#f3d7de]',
    'dot' => 'bg-[#d98ca6]',
    'gate' => 'bg-[#fff6f7]',
    'gateName' => 'text-[#8f4257]',
    'gateAmp' => 'text-[#d98ca6]',
    'gateMuted' => 'text-[#c096a5]',
    'gateButton' => 'bg-[#d98ca6] text-white shadow-lg shadow-[#d98ca6]/35',
]])
