{{-- Klasik: cream paper, maroon ink, gold leaf. --}}
@include('sites.partials.card', ['site' => $site, 'preview' => $preview, 'palette' => [
    'tone' => 'light',
    'eyebrow' => 'Walimatulurus',
    'page' => 'bg-[#fbf6ec] text-[#4a2c1d]',
    'name' => 'text-[#7a2230]',
    'amp' => 'text-[#c19a4b]',
    'body' => 'text-[#7b5c4a]',
    'muted' => 'text-[#b0937c]',
    'floral' => '#a8434f',
    'accent' => '#c19a4b',
    'petals' => ['#e8c9a0', '#d8a7ae', '#f0dcc0'],
    'petalOpacity' => '0.55',
    'panel' => 'border-[#e6d5bd] bg-white/70',
    'button' => 'bg-[#7a2230] text-white hover:bg-[#671b27]',
    'ring' => 'ring-[#e6d5bd]',
    'rail' => 'border-[#e6d5bd]',
    'dot' => 'bg-[#c19a4b]',
    'gate' => 'bg-[#fbf6ec]',
    'gateName' => 'text-[#7a2230]',
    'gateAmp' => 'text-[#c19a4b]',
    'gateMuted' => 'text-[#b0937c]',
    'gateButton' => 'bg-[#7a2230] text-white shadow-lg shadow-[#7a2230]/25',
]])
