{{-- Malam: midnight blue with gold, for an evening reception. --}}
@include('sites.partials.card', ['site' => $site, 'preview' => $preview, 'palette' => [
    'tone' => 'dark',
    'eyebrow' => 'Resepsi Malam',
    'page' => 'bg-[#0d1024] text-white/80',
    'name' => 'text-white',
    'amp' => 'text-[#d9b06a]',
    'body' => 'text-white/65',
    'muted' => 'text-white/40',
    'floral' => '#d9b06a',
    'accent' => '#f0d9a8',
    'petals' => ['#d9b06a', '#f0d9a8', '#8b93c9'],
    'petalOpacity' => '0.45',
    'panel' => 'border-white/12 bg-white/5',
    'button' => 'bg-[#d9b06a] text-[#0d1024] hover:bg-[#e6c489]',
    'ring' => 'ring-white/20',
    'rail' => 'border-white/15',
    'dot' => 'bg-[#d9b06a]',
    'gate' => 'bg-[#0d1024]',
    'gateName' => 'text-white',
    'gateAmp' => 'text-[#d9b06a]',
    'gateMuted' => 'text-white/40',
    'gateButton' => 'bg-[#d9b06a] text-[#0d1024] shadow-lg shadow-[#d9b06a]/25',
]])
