{{-- Moden: warm white, charcoal ink, quiet sage. --}}
@include('sites.partials.card', ['site' => $site, 'preview' => $preview, 'palette' => [
    'tone' => 'light',
    'eyebrow' => 'The Wedding Of',
    'page' => 'bg-[#faf9f6] text-neutral-800',
    'name' => 'text-neutral-900',
    'amp' => 'text-[#93a68b]',
    'body' => 'text-neutral-600',
    'muted' => 'text-neutral-400',
    'floral' => '#93a68b',
    'accent' => '#c2b49a',
    'petals' => ['#dfe6da', '#e8e2d5', '#cfd8c8'],
    'petalOpacity' => '0.5',
    'panel' => 'border-neutral-200 bg-white',
    'button' => 'bg-neutral-900 text-white hover:bg-neutral-800',
    'ring' => 'ring-neutral-200',
    'rail' => 'border-neutral-200',
    'dot' => 'bg-[#93a68b]',
    'gate' => 'bg-[#faf9f6]',
    'gateName' => 'text-neutral-900',
    'gateAmp' => 'text-[#93a68b]',
    'gateMuted' => 'text-neutral-400',
    'gateButton' => 'bg-neutral-900 text-white shadow-lg shadow-neutral-900/20',
]])
